[general]
#log_file = "/var/log/service/node-alert-responder.log"
log_file = "/tmp/node-alert-responder.log"
initial_wait_time = "2s"

[certs]
cert_file = "/box/etc/pki/node-alert-responder.crt"
key_file = "/box/etc/pki/node-alert-responder.key"
ca_cert_file = "/box/etc/pki/node-alert-responder.pem"

[server]
#Healthz and profiling endpoint
ServerAddress = "0.0.0.0"
ServerPort    = "8080"

[receiver]
ReceiverAddress = "0.0.0.0"
ReceiverPort = "9090"

[worker]
WorkerPort = "9191"
WorkerNamespace = "node-alert-worker"
MaxTasks = 2

[alerts]
AlertsNamespace  = "node-alert-generator" #node-problem-detector
AlertConfigMap   = "npd-alerts"

[results]
ResultsNamespace = "node-alert-responder"
ResultsConfigMap = "nro-results"
ResultsUpdateInterval = "30s"

[cache]
CacheExpireInterval = "48h"
